name: ecommerce_app
description: Proyecto Gabriel."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0

  http: ^1.2.1

  provider: ^6.1.2

  firebase_core:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/LoginRegisterMainPageBackground.jpg
    - lib/assets/images/Login_BG.jpg

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: lib/assets/fonts/RobotoSlab-Medium.ttf
